### ISSUE TITLE
MxBuild error will not quit the process

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/docker-mendix-buildpack#48] opened 2018-07-17 11:01 UTC
Step 11 failed in our situation but won't quit the build process and concludes a successful build which is not. Is it possible to fix that? 

...
 Step 11/20 : RUN "/buildpack/compilation" /build /cache &&   rm -fr /cache /tmp/javasdk /tmp/opt
...

whole log below:

--------------------

Checked out revision 295.
Check for presence of MPR file
Cloning into 'docker-mendix-buildpack'...
Sending build context to Docker daemon  111.9MB

Step 1/20 : FROM mendix/rootfs
latest: Pulling from mendix/rootfs
28bfaceaff9b: Pulling fs layer
ac540055f2f8: Pulling fs layer
2965585ef8b8: Pulling fs layer
2416bb9f3ad2: Pulling fs layer
93b55a6a6807: Pulling fs layer
809de0bb68c7: Pulling fs layer
2416bb9f3ad2: Waiting
93b55a6a6807: Waiting
809de0bb68c7: Waiting
ac540055f2f8: Verifying Checksum
ac540055f2f8: Download complete
2965585ef8b8: Verifying Checksum
2965585ef8b8: Download complete
2416bb9f3ad2: Verifying Checksum
2416bb9f3ad2: Download complete
93b55a6a6807: Verifying Checksum
93b55a6a6807: Download complete
28bfaceaff9b: Verifying Checksum
28bfaceaff9b: Download complete
809de0bb68c7: Verifying Checksum
809de0bb68c7: Download complete
28bfaceaff9b: Pull complete
ac540055f2f8: Pull complete
2965585ef8b8: Pull complete
2416bb9f3ad2: Pull complete
93b55a6a6807: Pull complete
809de0bb68c7: Pull complete
Digest: sha256:1ba5fd3b5b7dfb923165349b5047f7465f3a19e9a7ae640551df74b7d5ffb482
Status: Downloaded newer image for mendix/rootfs:latest
 ---> da5a5683d00e
Step 2/20 : LABEL Author="Mendix Digital Ecosystems"
 ---> Running in 2af5caeda662
Removing intermediate container 2af5caeda662
 ---> a425d19206b7
Step 3/20 : LABEL maintainer="digitalecosystems@mendix.com"
 ---> Running in 972599b8489c
Removing intermediate container 972599b8489c
 ---> 20d7680e8282
Step 4/20 : ARG BUILD_PATH=project
 ---> Running in 840bd24ea5c4
Removing intermediate container 840bd24ea5c4
 ---> 81f047c9a147
Step 5/20 : RUN mkdir -p buildpack/.local &&    (wget -qO- https://github.com/mendix/cf-mendix-buildpack/archive/v1.9.2.tar.gz    | tar xvz -C buildpack --strip-components 1)
 ---> Running in b7a0e3ea5500
cf-mendix-buildpack-1.9.2/.gitignore
cf-mendix-buildpack-1.9.2/.travis.yml
cf-mendix-buildpack-1.9.2/README.md
cf-mendix-buildpack-1.9.2/bin/
cf-mendix-buildpack-1.9.2/bin/compile
cf-mendix-buildpack-1.9.2/bin/detect
cf-mendix-buildpack-1.9.2/bin/mendix-logfilter
cf-mendix-buildpack-1.9.2/bin/release
cf-mendix-buildpack-1.9.2/docs/
cf-mendix-buildpack-1.9.2/docs/continuous-integration.md
cf-mendix-buildpack-1.9.2/lib/
cf-mendix-buildpack-1.9.2/lib/buildpackutil.py
cf-mendix-buildpack-1.9.2/lib/datadog.py
cf-mendix-buildpack-1.9.2/lib/httplib2/
cf-mendix-buildpack-1.9.2/lib/httplib2/__init__.py
cf-mendix-buildpack-1.9.2/lib/httplib2/cacerts.txt
cf-mendix-buildpack-1.9.2/lib/httplib2/iri2uri.py
cf-mendix-buildpack-1.9.2/lib/httplib2/socks.py
cf-mendix-buildpack-1.9.2/lib/instadeploy.py
cf-mendix-buildpack-1.9.2/lib/m2ee/
cf-mendix-buildpack-1.9.2/lib/m2ee/__init__.py
cf-mendix-buildpack-1.9.2/lib/m2ee/client.py
cf-mendix-buildpack-1.9.2/lib/m2ee/client_errno.py
cf-mendix-buildpack-1.9.2/lib/m2ee/config.py
cf-mendix-buildpack-1.9.2/lib/m2ee/core.py
cf-mendix-buildpack-1.9.2/lib/m2ee/log.py
cf-mendix-buildpack-1.9.2/lib/m2ee/munin.py
cf-mendix-buildpack-1.9.2/lib/m2ee/nagios.py
cf-mendix-buildpack-1.9.2/lib/m2ee/pgutil.py
cf-mendix-buildpack-1.9.2/lib/m2ee/profile.py
cf-mendix-buildpack-1.9.2/lib/m2ee/profileutil.py
cf-mendix-buildpack-1.9.2/lib/m2ee/profileutildp.py
cf-mendix-buildpack-1.9.2/lib/m2ee/runner.py
cf-mendix-buildpack-1.9.2/lib/m2ee/smaps.py
cf-mendix-buildpack-1.9.2/lib/m2ee/util.py
cf-mendix-buildpack-1.9.2/lib/m2ee/version.py
cf-mendix-buildpack-1.9.2/lib/metrics.py
cf-mendix-buildpack-1.9.2/lib/mxbuild.py
cf-mendix-buildpack-1.9.2/lib/nginx.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libcom_err-beb60336.so.2.1
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libcrypto-34813f62.so.1.0.2l
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libgssapi_krb5-174f8956.so.2.2
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libk5crypto-622ef25b.so.3.1
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libkeyutils-1-ff31573b.2.so
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libkrb5-fb0d2caa.so.3.3
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libkrb5support-d7ce89d4.so.0.1
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/liblber-2-14d46c3c.4.so.2.10.7
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libldap_r-2-c9812571.4.so.2.10.7
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libpq-909a53d8.so.5.10
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libsasl2-e96a0dbf.so.2.0.22
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libselinux-cf8f9094.so.1
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libsepol-b4f5b513.so.1
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libssl-fad88670.so.1.0.2l
cf-mendix-buildpack-1.9.2/lib/psycopg2/.libs/libz-a147dcb0.so.1.2.3
cf-mendix-buildpack-1.9.2/lib/psycopg2/__init__.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/_ipaddress.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/_json.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/_psycopg.so
cf-mendix-buildpack-1.9.2/lib/psycopg2/_range.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/errorcodes.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/extensions.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/extras.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/pool.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/psycopg1.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/sql.py
cf-mendix-buildpack-1.9.2/lib/psycopg2/tz.py
cf-mendix-buildpack-1.9.2/lib/requests/
cf-mendix-buildpack-1.9.2/lib/requests/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/adapters.py
cf-mendix-buildpack-1.9.2/lib/requests/api.py
cf-mendix-buildpack-1.9.2/lib/requests/auth.py
cf-mendix-buildpack-1.9.2/lib/requests/cacert.pem
cf-mendix-buildpack-1.9.2/lib/requests/certs.py
cf-mendix-buildpack-1.9.2/lib/requests/compat.py
cf-mendix-buildpack-1.9.2/lib/requests/cookies.py
cf-mendix-buildpack-1.9.2/lib/requests/exceptions.py
cf-mendix-buildpack-1.9.2/lib/requests/hooks.py
cf-mendix-buildpack-1.9.2/lib/requests/models.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/
cf-mendix-buildpack-1.9.2/lib/requests/packages/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/big5freq.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/big5prober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/chardetect.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/chardistribution.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/charsetgroupprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/charsetprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/codingstatemachine.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/compat.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/constants.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/cp949prober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/escprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/escsm.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/eucjpprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/euckrfreq.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/euckrprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/euctwfreq.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/euctwprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/gb2312freq.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/gb2312prober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/hebrewprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/jisfreq.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/jpcntx.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/langbulgarianmodel.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/langcyrillicmodel.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/langgreekmodel.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/langhebrewmodel.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/langhungarianmodel.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/langthaimodel.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/latin1prober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/mbcharsetprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/mbcsgroupprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/mbcssm.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/sbcharsetprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/sbcsgroupprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/sjisprober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/universaldetector.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/chardet/utf8prober.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/_collections.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/connection.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/connectionpool.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/contrib/
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/contrib/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/contrib/ntlmpool.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/contrib/pyopenssl.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/exceptions.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/fields.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/filepost.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/ordered_dict.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/six.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/ssl_match_hostname/
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/poolmanager.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/request.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/response.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/__init__.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/connection.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/request.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/response.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/retry.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/ssl_.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/timeout.py
cf-mendix-buildpack-1.9.2/lib/requests/packages/urllib3/util/url.py
cf-mendix-buildpack-1.9.2/lib/requests/sessions.py
cf-mendix-buildpack-1.9.2/lib/requests/status_codes.py
cf-mendix-buildpack-1.9.2/lib/requests/structures.py
cf-mendix-buildpack-1.9.2/lib/requests/utils.py
cf-mendix-buildpack-1.9.2/lib/yaml/
cf-mendix-buildpack-1.9.2/lib/yaml/__init__.py
cf-mendix-buildpack-1.9.2/lib/yaml/composer.py
cf-mendix-buildpack-1.9.2/lib/yaml/constructor.py
cf-mendix-buildpack-1.9.2/lib/yaml/cyaml.py
cf-mendix-buildpack-1.9.2/lib/yaml/dumper.py
cf-mendix-buildpack-1.9.2/lib/yaml/emitter.py
cf-mendix-buildpack-1.9.2/lib/yaml/error.py
cf-mendix-buildpack-1.9.2/lib/yaml/events.py
cf-mendix-buildpack-1.9.2/lib/yaml/loader.py
cf-mendix-buildpack-1.9.2/lib/yaml/nodes.py
cf-mendix-buildpack-1.9.2/lib/yaml/parser.py
cf-mendix-buildpack-1.9.2/lib/yaml/reader.py
cf-mendix-buildpack-1.9.2/lib/yaml/representer.py
cf-mendix-buildpack-1.9.2/lib/yaml/resolver.py
cf-mendix-buildpack-1.9.2/lib/yaml/scanner.py
cf-mendix-buildpack-1.9.2/lib/yaml/serializer.py
cf-mendix-buildpack-1.9.2/lib/yaml/tokens.py
cf-mendix-buildpack-1.9.2/m2ee.yaml
cf-mendix-buildpack-1.9.2/newrelic/
cf-mendix-buildpack-1.9.2/newrelic/newrelic.jar
cf-mendix-buildpack-1.9.2/newrelic/newrelic.yml
cf-mendix-buildpack-1.9.2/nginx/
cf-mendix-buildpack-1.9.2/nginx/conf/
cf-mendix-buildpack-1.9.2/nginx/conf/mime.types
cf-mendix-buildpack-1.9.2/nginx/conf/nginx.conf
cf-mendix-buildpack-1.9.2/nginx/conf/proxy_params
cf-mendix-buildpack-1.9.2/nginx/monsters/
cf-mendix-buildpack-1.9.2/nginx/monsters/502-ff-app.html
cf-mendix-buildpack-1.9.2/nginx/monsters/503-appnode-app.html
cf-mendix-buildpack-1.9.2/nginx/monsters/503-appnode-catchall.html
cf-mendix-buildpack-1.9.2/nginx/monsters/503-ff-catchall.html
cf-mendix-buildpack-1.9.2/nginx/monsters/mx_error_page/
cf-mendix-buildpack-1.9.2/nginx/monsters/mx_error_page/mendix.png
cf-mendix-buildpack-1.9.2/nginx/monsters/mx_error_page/running.png
cf-mendix-buildpack-1.9.2/nginx/monsters/mx_error_page/server.png
cf-mendix-buildpack-1.9.2/start.py
cf-mendix-buildpack-1.9.2/tests/
cf-mendix-buildpack-1.9.2/tests/README.md
cf-mendix-buildpack-1.9.2/tests/cleanup.sh
cf-mendix-buildpack-1.9.2/tests/create-app-services.sh
cf-mendix-buildpack-1.9.2/tests/delete-app.sh
cf-mendix-buildpack-1.9.2/tests/requirements.txt
cf-mendix-buildpack-1.9.2/tests/run.sh
cf-mendix-buildpack-1.9.2/tests/usecase/
cf-mendix-buildpack-1.9.2/tests/usecase/basetest.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_access_restrictions.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_buildstatus_callback.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_constants.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_custom_runtime_settings.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_emit_metrics.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_fastdeploy.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_java_crash_restarts_process.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_logging.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_mda_app_deployed.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_mda_app_deployed_multiple_instances.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_mono4.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_mpk_app_deployed.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_mxadmin_exposed_authorized.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_sampledata.py
cf-mendix-buildpack-1.9.2/tests/usecase/test_terminate_process_on_crashing_app.py
Removing intermediate container b7a0e3ea5500
 ---> 7a52c9549006
Step 6/20 : COPY scripts/compilation /buildpack
 ---> cf5050fe92e3
Step 7/20 : ENV PYTHONPATH "/buildpack/lib/"
 ---> Running in 8491e4ee7982
Removing intermediate container 8491e4ee7982
 ---> 62969288dfeb
Step 8/20 : RUN mkdir build cache
 ---> Running in c5a8a550d41f
Removing intermediate container c5a8a550d41f
 ---> 6645458270d4
Step 9/20 : COPY $BUILD_PATH build
 ---> f1fc026cd77f
Step 10/20 : WORKDIR /buildpack
Removing intermediate container 30f96f288aae
 ---> 676286f4be53
**Step 11/20 : RUN "/buildpack/compilation" /build /cache &&   rm -fr /cache /tmp/javasdk /tmp/opt**
 ---> Running in b0bdeead129f
INFO: Mendix project compilation phase...
INFO: source push detected
INFO: Selecting Mono Runtime: mono-4.6.2.16
tar: lib/libgdiplus.so: Wrote only 9216 of 10240 bytes
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/buildpack/bin/compile", line 283, in <module>
    run_mx_build()
  File "/buildpack/bin/compile", line 184, in run_mx_build
    mono_location = buildpackutil.ensure_and_get_mono(mx_version, CACHE_DIR)
  File "/buildpack/lib/buildpackutil.py", line 386, in ensure_and_get_mono
    cache_dir
  File "/buildpack/lib/buildpackutil.py", line 185, in download_and_unpack
    subprocess.check_call(unpack_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', 'xf', '/cache/bust/mono-4.6.2.16-mx.tar.gz', '-C', '/tmp/opt/mono-4.6.2.16', '--strip', '1']' returned non-zero exit status 2
Removing intermediate container b0bdeead129f
 ---> 13be7bc995a4
Step 12/20 : ENV PORT 80
 ---> Running in e44a0870ef1d
Removing intermediate container e44a0870ef1d
 ---> 7847fc84780f
Step 13/20 : EXPOSE $PORT
 ---> Running in 9a62ac0ce4ca
Removing intermediate container 9a62ac0ce4ca
 ---> bfe654092ea2
Step 14/20 : RUN mkdir -p "/.java/.userPrefs/com/mendix/core"
 ---> Running in 5f96592d5ab9
Removing intermediate container 5f96592d5ab9
 ---> 95bedbf52a01
Step 15/20 : RUN mkdir -p "/root/.java/.userPrefs/com/mendix/core"
 ---> Running in 493a5cded25a
Removing intermediate container 493a5cded25a
 ---> 0b14b9f12767
Step 16/20 : RUN ln -s "/.java/.userPrefs/com/mendix/core/prefs.xml" "/root/.java/.userPrefs/com/mendix/core/prefs.xml"
 ---> Running in f0d94baf0272
Removing intermediate container f0d94baf0272
 ---> 33f2a3c551e5
Step 17/20 : COPY scripts/ /build
 ---> 28ad681b0a9c
Step 18/20 : WORKDIR /build
Removing intermediate container 4abfe8a2b2f8
 ---> b9a6b039746f
Step 19/20 : RUN chmod u+x startup
 ---> Running in 3af4907d2468
Removing intermediate container 3af4907d2468
 ---> fce1c92eeee1
Step 20/20 : ENTRYPOINT ["/build/startup","/buildpack/start.py"]
 ---> Running in 8b1d8180d04f
Removing intermediate container 8b1d8180d04f
 ---> 29eca2096c25
Successfully built 29eca2096c25

**Comment by dudk** [comment] 2019-02-27 09:56
This is a duplicate of #16 

Please subscribe to that issue if you want to track the progress.

**Closed** 2019-02-27 09:56 UTC
